name: main
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        version: [3.7, 3.x]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.version}}
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - uses: tonynv/asciidoctor-action@master
      - run: pip install pyyaml
      - run: npm i -g downdoc
      - run: ./convert-all.sh
      - run: echo "$PWD/node_modules/.bin" >> "$GITHUB_PATH"
      - run: python plano test
